### ISSUE TITLE
How do I run it ?

### ISSUE THREAD

**Issue by shirishag75** [FedericoCeratto/desktop-security-assistant#1]
Hi there, 
How do I run it ?

Doing ' `~/games/desktop-security-assistant/desktop_security_assistant$ python main.py` gives :-

```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from setproctitle import setproctitle
ImportError: No module named setproctitle
```

Going to the previous directory shows :-

```
~/games/desktop-security-assistant]$ python setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help 
```

Looking forward to know as to how to fix it. Running python 2.7.9.

**Comment by FedericoCeratto** [comment]
How are you installing the dependencies?
If on a Debian (or derivative) system, apt-get install python-yaml python-setproctitle python-gi

**Comment by shirishag75** [comment]
ah, thanx. Didn't see that. Only `python-setproctitle` was missing. Once installed it, it worked.
